---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args:
    - "--context=https://github.com/adekoyadapo/360ace.git"
    - "--dockerfile=/Workspace/Dockerfile"
    - "--insecure"
    - "--insecure-pull"
    - "--skip-tls-verify"
    - "--skip-tls-verify-pull"
    - "--insecure-registry=10-0-10-180.sslip.io:5000"
    - "--destination=10-0-10-180.sslip.io:5000/company-site:v1"
    - "--git=branch=dev"
  restartPolicy: Never