---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args: 
    - "--context=git://gitea.10-0-10-50.sslip.io/gitea_admin/360ace.git#refs/heads/dev"
    - "--dockerfile=/Workspace/Dockerfile"
    - "--insecure"
    - "--insecure-pull"
    - "--skip-tls-verify"
    - "--skip-tls-verify-pull"
    - "--insecure-registry=k3d-devcluster-registry:5000"
    - "--destination=k3d-devcluster-registry:5000/company-site:v1"
  restartPolicy: Never
